services:
  portfolio:
    image: ghcr.io/alexdalat/portfolio:latest
    ports:
      - "3000:3000"
    volumes:
      - ${PORTFOLIO_RESUME_FILE:-./public/Resume.pdf}:/app/public/resume.pdf:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"