services:
  portfolio:
    image: ghcr.io/alexdalat/portfolio:latest
    ports:
      - "${PORT_BIND:-3000}:3000"
    volumes:
      - /home/alex/syncthing/Personal/Work/Resume/:/app/public/Resume/:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
